version: "3.7"
services:
    shorten-link:
        build:
            context: ./
            dockerfile: ./app.Dockerfile
        container_name: shorten-link
        ports:
            - 8080:8080
        environment: 
            DATABASE_HOST: 192.168.0.98
            DATABASE_PORT: 5000